id: DA85C7B87
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:05:33+00:00'
last_modified: '2022-05-26T08:21:29.764876+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    057e:
      image_group_id: I1PD95859
      title: རྡོ་རྗེ་ནག་པོ་ཆེན་པོའི་བསྟོད་པ་བརྒྱད་པ།
      total_pages: 1856
      order: 14
      base_file: 057e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
